name: dev

on:
  push:
    branches:
      - feature/**
      - fix/**

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: install
        run: |
          yarn install
      - name: licence check
        run: |
          summary=`yarn license-checker --production --summary`
          ret=`cat summary | grep -v LGPL | grep -e GPL | wc -l`
          exit $ret
      - name: build
        run: |
          yarn build:dev
        env:
          CI: true
      - name: can i publish
        run: yarn run can-npm-publish
